
name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs every 6 hours (you can change it)
  workflow_dispatch:        # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: VivekDhobale
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Move files to root
        run: |
          mv dist/* .

      - name: Commit and push snake files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git commit -m "Updated Snake animation"
          git push
