name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every midnight
  workflow_dispatch:     # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake (SVG + GIF)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: VivekDhobale-VivekXploit
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
